# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pr:
  autoCancel: false
  branches:
    include:
    - '*'

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    projects: '**/*.Tests.csproj'
    arguments: '--configuration Release'
    
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: 'pack'
    packagesToPack: 'src/Geko.HttpClientService/Geko.HttpClientService.csproj'
    configuration: 'Release'
    versioningScheme: 'off'

- powershell: |
    choco install docfx -y
    docfx docfx_project/docfx.json
    if ($lastexitcode -ne 0){
      throw ("Error generating document")
    }
  displayName: "Documentation"
